server.port=8085

# Configuration de la Base de Données Oracle
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=system
spring.datasource.password=votre_mot_de_passe
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connexion à l'annuaire Eureka du groupe
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/