server.port=8085

# Connexion PostgreSQL alignée sur le Docker du groupe
spring.datasource.url=jdbc:postgresql://localhost:5433/transaction_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enregistrement Eureka
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/
eureka.instance.prefer-ip-address=true