# Port sur lequel votre service va s'exécuter
server.port=8085

# Liaison avec l'annuaire Eureka
eureka.client.service-url.defaultZone=http://localhost:8081/eureka/

# Configuration de votre base de données (Exemple JPA)
spring.datasource.url=jdbc:mysql://localhost:3306/db_transactions
spring.datasource.username=root
spring.datasource.password=votre_mot_de_passe
spring.jpa.hibernate.ddl-auto=update